apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: postgres-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres 
          image: postgres:15
          ports: 
          - containerPort: 5432
            name: post-db 
          volumeMount: 
          - name: postgres-storag
            mountPath: /var/lib/postgresql/data
          env:
            POSTGRES_DB = coordinates_db  
            POSTGRES_USER = postgres  
            POSTGRES_PASSWORD = postgres
  volumeClaimTemplate:
  - metadata:
      name: postgres-storag
    spec:
      accessMode: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi



